#jmeter
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/jmeter.git
  path: roles/

#robot_framework
- src: git+ssh://gitlab@git.forgeservicelab.fi:10022/ansible-roles/robot_framework.git
  path: roles/
